# Generated by Django 5.2.4 on 2025-08-21 10:45

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0020_alter_variety_add_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producer",
            options={"ordering": ("region", "name")},
        ),
    ]
