# Generated by Django 5.2.4 on 2025-08-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0021_alter_producer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variety",
            options={"ordering": ("name",)},
        ),
    ]
