# Generated by Django 5.2.4 on 2025-08-21 10:55

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0022_alter_variety_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wine",
            options={
                "ordering": ("section__order", "subsection__order", "line_num_tot")
            },
        ),
    ]
