# Generated by Django 5.2.4 on 2025-08-21 10:57

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wine_wiki", "0023_alter_wine_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wine",
            name="is_published",
        ),
    ]
