# Generated by Django 5.2.4 on 2025-08-21 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0025_wine_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="price",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
