# Generated by Django 5.2.4 on 2025-08-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0026_alter_wine_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="WineListDisplay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_num_tot", models.IntegerField(default=-1, null=True)),
                ("page_num", models.IntegerField(default=-1)),
                ("page_line_num", models.IntegerField(default=-1)),
                ("subsubsection", models.CharField(default="")),
                (
                    "section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wine_wiki.section",
                    ),
                ),
                (
                    "subsection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wine_wiki.subsection",
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wine_wiki.wine",
                    ),
                ),
            ],
        ),
    ]
