# Generated by Django 5.2.4 on 2025-08-21 11:05

import django.db.models.deletion
from django.db import migrations, models

from wine_wiki.models import BennelongWineList


def populate_bennelong_wine_list(apps, schema_editor):
    Wine = apps.get_model("wine_wiki", "Wine")
    BennelongWineList = apps.get_model("wine_wiki", "BennelongWineList")
    Section = apps.get_model("wine_wiki", "Section")
    SubSection = apps.get_model("wine_wiki", "SubSection")

    bennelong_wine_list_values = Wine.objects.values(
        "line_num_tot",
        "page_num",
        "page_line_num",
        "section",
        "subsection",
        "subsubsection",
        "id",
    )

    for row in bennelong_wine_list_values:
        try:
            section = Section.objects.get(pk=row["section"])
        except Exception as e:
            breakpoint()
            raise e

        try:
            subsection = SubSection.objects.get(pk=row["subsection"])
        except Exception as e:
            breakpoint()
            raise e

        try:
            wine = Wine.objects.get(id=row["id"])
        except Exception as e:
            breakpoint()
            raise e

        bennelong_wine_list_row = BennelongWineList(
            line_num_tot=row["line_num_tot"],
            page_num=row["page_num"],
            page_line_num=row["page_line_num"],
            section=section,
            subsection=subsection,
            subsubsection=row["subsubsection"],
            wine=wine,
        )

        try:
            bennelong_wine_list_row.save()
        except Exception as e:
            breakpoint()


def reverse_populate_bennelong_wine_list(apps, schema_editor):
    BennelongWineList = apps.get_model("wine_wiki", "BennelongWineList")

    BennelongWineList.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0027_bennelongwinelist"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_bennelong_wine_list,
            reverse_code=reverse_populate_bennelong_wine_list,
        ),
    ]
