# Generated by Django 5.2.4 on 2025-08-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0028_fill_bennelong_wine_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bennelongwinelist',
            options={'ordering': ('section__order', 'subsection__order', 'line_num_tot')},
        ),
        migrations.AlterModelOptions(
            name='wine',
            options={},
        ),
        migrations.RemoveField(
            model_name='wine',
            name='line_num_tot',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='page_line_num',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='page_num',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='section',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='subsection',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='subsubsection',
        ),
    ]
