# Generated by Django 5.2.4 on 2025-09-15 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0029_alter_bennelongwinelist_options_alter_wine_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineListRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField()),
                ('pub_date', models.DateField()),
                ('run_dt', models.DateTimeField()),
                ('line_num_tot', models.IntegerField()),
                ('vintage', models.CharField()),
                ('prod_wine_name', models.CharField()),
                ('geo_int', models.CharField()),
                ('vol', models.CharField()),
                ('price', models.IntegerField()),
                ('section_path', models.CharField()),
                ('page_number', models.IntegerField()),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wine_wiki.wine')),
                ('wine_list_display', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wine_wiki.winelistdisplay')),
            ],
        ),
    ]
