# Generated by Django 5.2.4 on 2025-09-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0030_winelistraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineListUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='wine_list/')),
                ('name', models.CharField()),
                ('dt_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
