# Generated by Django 5.2.4 on 2025-09-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0031_winelistupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winelistupload',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
