# Generated by Django 5.2.4 on 2025-09-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0032_alter_winelistupload_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='winelistraw',
            name='winelistupload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.winelistupload'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='winelistraw',
            name='wine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wine_wiki.wine'),
        ),
    ]
