# Generated by Django 5.2.4 on 2025-09-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0033_winelistraw_winelistupload_alter_winelistraw_wine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winelistraw',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
