# Generated by Django 5.2.4 on 2025-10-23 23:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0035_alter_winelistraw_wine_list_display"),
    ]

    operations = [
        migrations.CreateModel(
            name="WineListDisplay",
            fields=[
                (
                    "wine",
                    models.ForeignKey(
                        to="wine_wiki.wine", on_delete=models.CASCADE, null=True
                    ),
                ),
                (
                    "winelistraw",
                    models.ForeignKey(
                        to="wine_wiki.winelistraw", on_delete=models.CASCADE
                    ),
                ),
                ("line_num_tot", models.IntegerField(default=-1)),
                ("vintage", models.CharField(default="")),
                ("prod_wine_name", models.CharField(default="")),
                ("geo_int", models.CharField(default="")),
                ("vol", models.CharField(default="")),
                ("price", models.IntegerField(default=-1)),
                ("section_path", models.CharField(default="")),
                ("page_number", models.IntegerField(default=-1)),
                ("wine_type", models.CharField(default="")),
                ("origin", models.CharField(default="")),
                ("varietal", models.CharField(default="")),
            ],
        ),
    ]
