# Generated by Django 5.2.4 on 2025-09-16 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine_wiki", "0034_alter_winelistraw_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winelistraw",
            name="wine_list_display",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="wine_wiki.winelistdisplay",
            ),
        ),
    ]
