# Generated by Django 5.2.4 on 2025-09-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0036_alter_winelistdisplay_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winelistdisplay',
            name='line_num_tot',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='winelistdisplay',
            name='page_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='winelistdisplay',
            name='price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='winelistdisplay',
            name='pub_date',
            field=models.DateTimeField(default=(1970, 1, 1, 0, 0, 0, 3, 1, 0)),
        ),
        migrations.AlterField(
            model_name='winelistraw',
            name='price',
            field=models.IntegerField(default=-1),
        ),
    ]
