# Generated by Django 5.2.4 on 2025-09-19 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0037_alter_winelistdisplay_line_num_tot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winelistdisplay',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='winelistdisplay',
            name='winelistraw',
        ),
        migrations.RemoveField(
            model_name='winelistraw',
            name='filepath',
        ),
        migrations.RemoveField(
            model_name='winelistraw',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='winelistraw',
            name='run_dt',
        ),
        migrations.RemoveField(
            model_name='winelistraw',
            name='winelistupload',
        ),
        migrations.CreateModel(
            name='WineListEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(default='')),
                ('pub_date', models.DateTimeField()),
                ('run_dt', models.DateTimeField()),
                ('winelistupload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.winelistupload')),
            ],
        ),
        migrations.AddField(
            model_name='winelistdisplay',
            name='winelistedition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.winelistedition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winelistraw',
            name='winelistedition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.winelistedition'),
            preserve_default=False,
        ),
    ]
