# Generated by Django 5.2.4 on 2025-09-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0038_remove_winelistdisplay_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winelistedition',
            name='pub_date',
            field=models.DateTimeField(unique=True),
        ),
    ]
