# Generated by Django 5.2.4 on 2025-09-20 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0039_alter_winelistedition_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winelistdisplay',
            name='winelistedition',
        ),
        migrations.AddField(
            model_name='winelistdisplay',
            name='winelistraw',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.winelistraw'),
            preserve_default=False,
        ),
    ]
