# Generated by Django 5.2.4 on 2025-09-21 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0040_remove_winelistdisplay_winelistedition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuzzyMatchListWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wine_wiki.wine')),
                ('wine_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wine_wiki.winelistdisplay')),
            ],
        ),
    ]
