# Generated by Django 5.2.4 on 2025-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0041_fuzzymatchlistwiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuzzymatchlistwiki',
            name='wiki_choice',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuzzymatchlistwiki',
            name='wine_list_query',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
    ]
