# Generated by Django 5.2.4 on 2025-09-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0042_fuzzymatchlistwiki_wiki_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuzzymatchlistwiki',
            name='review',
            field=models.BooleanField(choices=[(True, 'Accept'), (False, 'Reject')], default=True),
            preserve_default=False,
        ),
    ]
