# Generated by Django 5.2.4 on 2025-09-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0043_fuzzymatchlistwiki_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuzzymatchlistwiki',
            name='review',
            field=models.BooleanField(choices=[(True, 'Accept'), (False, 'Reject')], null=True),
        ),
    ]
