# Generated by Django 5.2.4 on 2025-09-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0046_alter_fuzzymatchlistwiki_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuzzymatchlistwiki',
            name='review',
            field=models.BooleanField(default=False),
        ),
    ]
