# Generated by Django 5.2.4 on 2025-09-25 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0047_alter_fuzzymatchlistwiki_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFillPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.BooleanField(default=True)),
                ('wiki', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.wine')),
                ('wine_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.winelistdisplay')),
            ],
        ),
    ]
