# Generated by Django 5.2.4 on 2025-09-25 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0048_autofillpending'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFillEditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_left', to='wine_wiki.winelistdisplay')),
                ('edition_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_right', to='wine_wiki.winelistdisplay')),
            ],
        ),
    ]
