# Generated by Django 5.2.4 on 2025-09-25 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0049_autofilleditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofilleditions',
            name='edition_left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_left', to='wine_wiki.winelistedition'),
        ),
        migrations.AlterField(
            model_name='autofilleditions',
            name='edition_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_right', to='wine_wiki.winelistedition'),
        ),
    ]
