# Generated by Django 5.2.4 on 2025-09-28 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0050_alter_autofilleditions_edition_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autofillpending',
            name='wine_list',
        ),
        migrations.AddField(
            model_name='autofillpending',
            name='wine_list_left',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wld_left', to='wine_wiki.winelistdisplay'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autofillpending',
            name='wine_list_right',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wld_right', to='wine_wiki.winelistdisplay'),
            preserve_default=False,
        ),
    ]
