# Generated by Django 5.2.4 on 2025-09-28 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0051_remove_autofillpending_wine_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofillpending',
            name='autofilledition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.autofilleditions'),
            preserve_default=False,
        ),
    ]
