# Generated by Django 5.2.4 on 2025-09-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0052_autofillpending_autofilledition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFillRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='autofilleditions',
            name='autofillrun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.autofillrun'),
            preserve_default=False,
        ),
    ]
