# Generated by Django 5.2.4 on 2025-09-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0053_autofillrun_autofilleditions_autofillrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofillpending',
            name='wiki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.wine', unique=True),
        ),
        migrations.AlterField(
            model_name='autofillpending',
            name='wine_list_left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wld_left', to='wine_wiki.winelistdisplay', unique=True),
        ),
        migrations.AlterField(
            model_name='autofillpending',
            name='wine_list_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wld_right', to='wine_wiki.winelistdisplay', unique=True),
        ),
    ]
