# Generated by Django 5.2.4 on 2025-09-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0054_alter_autofillpending_wiki_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofillpending',
            name='autofilledition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.autofilleditions'),
        ),
        migrations.AlterField(
            model_name='autofillpending',
            name='wiki',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.wine'),
        ),
        migrations.AlterField(
            model_name='autofillpending',
            name='wine_list_left',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wld_left', to='wine_wiki.winelistdisplay'),
        ),
        migrations.AlterField(
            model_name='autofillpending',
            name='wine_list_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wld_right', to='wine_wiki.winelistdisplay'),
        ),
    ]
