# Generated by Django 5.2.4 on 2025-09-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0055_alter_autofillpending_autofilledition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofillpending',
            name='autofilledition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.autofilleditions'),
        ),
    ]
