# Generated by Django 5.2.4 on 2025-10-15 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0056_alter_autofillpending_autofilledition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuzzymatchlistwiki',
            name='wiki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.wine'),
        ),
        migrations.AlterField(
            model_name='fuzzymatchlistwiki',
            name='wine_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.winelistdisplay'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.section'),
        ),
        migrations.AlterField(
            model_name='subsubsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.section'),
        ),
        migrations.AlterField(
            model_name='subsubsection',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.subsection'),
        ),
        migrations.AlterField(
            model_name='winelistdisplay',
            name='wine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wine_wiki.wine'),
        ),
    ]
