# Generated by Django 5.2.4 on 2025-10-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0057_alter_fuzzymatchlistwiki_wiki_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winelistraw',
            name='origin',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='winelistraw',
            name='varietal',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='winelistraw',
            name='wine_type',
            field=models.CharField(default=''),
        ),
    ]
