# Generated by Django 5.2.4 on 2025-10-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_wiki', '0058_winelistraw_origin_winelistraw_varietal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winelistdisplay',
            name='origin',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='winelistdisplay',
            name='varietal',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='winelistdisplay',
            name='wine_type',
            field=models.CharField(default=''),
        ),
    ]
